export const intInRange = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1) + min);

export const namesRandomAttacks = [
  "Soul Eater",
  "Death's Scythe",
  "Death's Touch",
  "Soul Annihilator",
  "Darkness Hand of Death",
];

export const randomItemInArray = (array: any[]) =>
  array[Math.floor(Math.random() * array.length)];

export const namesTribesSkills = [
  "Llamado del Cóndor",
  "Sabiduría Ancestral",
  "Rastro del Puma",
  "Voz de la Pachamama",
  "Danza del Fuego",
  "Susurro del Viento",
  "Guerrero del Sol",
  "Vínculo del Totem",
  "Espíritu del Jaguar",
  "Flecha Estelar",
  "Canto de la Llama",
  "Visiones del Chamán",
  "Caminata Silenciosa",
  "Guardián de la Montaña",
  "Eco de los Antepasados",
  "Fuerza del Guanaco",
  "Reflejo del Agua",
  "Herencia del Inca",
  "Mirada del Águila",
  "Manos de Curandero",
  "Paso de la Vicuña",
  "Vuelo del Cóndor",
  "Lazo de la Comunidad",
  "Escudo de la Tierra",
  "Raíces Profundas",
  "Ritmo de la Puna",
  "Camino del Llareta",
  "Abrazo del Quebracho",
  "Luz de la Luna",
  "Senda del Coyuyo",
  "Máscara Ritual",
  "Carrera del Ñandú",
  "Respiración de la Selva",
  "Grito de la Taruca",
  "Huellas Ancestrales",
  "Espíritu del Zorro",
  "Arco Iris Andino",
  "Llamas del Altiplano",
  "Paso del Huemul",
  "Voz de la Tierra",
  "Sueño del Yaguareté",
  "Cántico del Río",
  "Ojos del Nocturno",
  "Danza de las Estrellas",
  "Lengua de la Llanura",
  "Despertar del Bosque",
  "Rugido del Pampas",
  "Garras del Andino",
  "Corazón del Desierto",
  "Meditación de la Sierra",
  "Sombra del Queñoa",
  "Aliento del Viento",
  "Cazador de la Luna",
  "Canto del Tero",
  "Luz del Amanecer",
  "Vigilante del Bosque",
  "Fuerza del Río",
  "Refugio del Cactus",
  "Manto de la Noche",
  "Espíritu de la Llanura",
  "Voz de la Cascada",
  "Senda del Pehuén",
  "Guardián del Valle",
  "Ritual de la Cosecha",
  "Caricia del Sol",
  "Vuelo del Chimango",
  "Paso del Gato Montés",
  "Susurro del Salitre",
  "Ritmo del Tambor",
  "Mirada de la Luna",
  "Abrazo del Algarrobo",
  "Canción del Viento",
  "Danza del Cóndor",
  "Vigilia del Guazú",
  "Poder del Silencio",
  "Alma del Bosque",
  "Camino del Rayo",
  "Destello del Lucero",
  "Serenidad de las Alturas",
  "Reflejo Lunar",
  "Guardián de la Sabana",
  "Camino del Toldo",
  "Voz del Anochecer",
  "Eco de la Quebrada",
  "Sueño del Pachón",
  "Ritual del Fuego",
  "Danza del Guazú",
  "Senda del Quirquincho",
  "Vuelo del Suri",
  "Camino de Estrellas",
  "Canto del Zorzal",
  "Resguardo del Mistol",
  "Vigilancia del Amanecer",
  "Espíritu del Cardón",
  "Rastro del Tatú",
  "Escudo Mapuche",
  "Llamado Guaraní",
  "Sabiduría Quechua",
  "Visión Tehuelche",
  "Fuerza Toba",
  "Canto Diaguita",
  "Paso Calchaquí",
  "Arte Mocoví",
  "Sueño Wichí",
  "Vuelo Selknam",
  "Resistencia Ranquel",
  "Agilidad Pilagá",
  "Espíritu Charrúa",
  "Caza Ona",
  "Ritual Puelche",
  "Habilidad Huarpe",
  "Trance Comechingón",
  "Curación Qom",
  "Vigilancia Chané",
  "Refugio Atacama",
  "Voz Kolla",
  "Destreza Omaguaca",
  "Ligereza Yámana",
  "Poder Tonocoté",
  "Intuición Lule",
  "Ritmo Vilela",
  "Danza Mbyá",
  "Fuego Ava",
  "Círculo Matara",
  "Melodía Kakán",
  "Vuelo del Nandubay",
  "Luz de Quirquincho",
  "Frescura del Ceibo",
  "Sombra de la Yarará",
  "Sueño del Yacaré",
  "Reflejo del Carpintero",
  "Habilidad del Guacamayo",
  "Fuerza del Tatú Carreta",
  "Agilidad del Vizcacha",
  "Visión del Puma",
  "Canto del Chucao",
  "Mística del Llao Llao",
  "Serenidad del Lago Nahuel",
  "Protección del Peñón",
  "Leyenda del Lanín",
  "Rugido del Volcán",
  "Armonía del Río Limay",
  "Misterio del Bosque Andino",
  "Paz del Lago Puelo",
  "Energía del Fitz Roy",
  "Vigor del Aconcagua",
  "Voz de la Puna",
  "Mirada del Condor",
  "Paso del Guanaco",
  "Espíritu del Copahue",
  "Senda del Coihue",
  "Fuerza del Arrayán",
  "Resistencia del Ñire",
  "Protección del Chañar",
  "Sabiduría del Algarrobo",
  "Calma del Quebracho",
  "Poder del Lapacho",
  "Esencia del Jacarandá",
  "Vigor del Palo Santo",
  "Misterio del Ombú",
  "Resiliencia del Caranday",
  "Gracia del Ñandú",
  "Velocidad del Cuis",
  "Agudeza del Zorro",
  "Sigilo del Pichiciego",
  "Fortaleza del Yaguareté",
  "Encanto del Colibrí",
  "Intuición de la Lechuza",
  "Pureza del Flamenco",
  "Elegancia del Cisne",
  "Habilidad del Carpintero",
  "Visión del Halconcito",
  "Precisión del Picaflor",
  "Destreza del Chimango",
  "Aguante del Lobo Marino",
  "Serenidad del Delfín",
  "Poder del Mar Argentino",
  "Mística de las Cataratas",
  "Belleza del Glaciar",
  "Fortaleza de la Pampa",
  "Misterio del Iberá",
  "Esplendor de Bariloche",
  "Encanto de Ushuaia",
  "Magia de la Quebrada",
  "Leyenda de Cafayate",
  "Mística de Tilcara",
  "Encanto de Salta",
  "Vigor de Mendoza",
  "Esencia de Córdoba",
  "Fuerza de La Rioja",
  "Honor de San Juan",
  "Tradición de San Luis",
  "Pureza de Santa Cruz",
  "Resiliencia de Chubut",
  "Belleza de Tierra del Fuego",
  "Misterio de Neuquén",
  "Serenidad de Río Negro",
  "Esplendor de Jujuy",
];

export const namesTribesCharacters: string[] = [
  "Aimé",
  "Ñancu",
  "Rayén",
  "Lihue",
  "Antu",
  "Calfu",
  "Eluney",
  "Lautaro",
  "Malén",
  "Yael",
  "Ayelén",
  "Damián",
  "Inti",
  "Killa",
  "Mama",
  "Nayra",
  "Pacha",
  "Quilla",
  "Sami",
  "Tupac",
  "Urpi",
  "Yaku",
  "Ara",
  "Cuarajhy",
  "Jacira",
  "Jasy",
  "Kurumi",
  "Mandu'a",
  "Nambi",
  "Pirakutu",
  "Pora",
  "Tapiti",
  "Yvoty",
  "Zaíra",
  "Aranwa",
  "Chaska",
  "Hatun",
  "Illari",
  "Kusiku",
  "Nayra",
  "P'iti",
  "Qhari",
  "Suyana",
  "T'ika",
  "Umiña",
  "Waraka",
  "Yana",
  "Zuni",
  "Aukán",
  "Chaltum",
  "Eirete",
  "Guaran",
  "Huenu",
  "Irupé",
  "Kai",
  "Lican",
  "Maité",
  "Nain",
  "Ollantay",
  "Pire",
  "Rumi",
  "Sayen",
  "Tacu",
  "Uru",
  "Vilca",
  "Wayra",
  "Yalit",
  "Zorai",
  "Anan",
  "Boirú",
  "Carai",
  "Dorá",
  "Etén",
  "Fetén",
  "Guaica",
  "Huayra",
  "Iberá",
  "Jarai",
  "Kereimba",
  "Liwen",
  "Mawiza",
  "Nimez",
  "Ombu",
  "Payun",
  "Quimey",
  "Rukha",
  "Sariri",
  "Tupã",
  "Ukumar",
  "Vilu",
  "Wenu",
  "Yagen",
  "Zahira",
  "Añi",
  "Betun",
  "Coyan",
  "Dahue",
  "Epu",
  "Foye",
  "Guanko",
  "Huemul",
  "Itro",
  "Jacha",
  "Kallfu",
  "Lemun",
  "Meli",
  "Ñire",
  "Orko",
  "Pehuen",
  "Quechu",
  "Relmu",
  "Suyai",
  "Trafün",
  "Ulmen",
  "Vero",
  "Willi",
  "Yastay",
  "Zorrito",
];

export const namesAnmilasTribes: string[] = [
  "Tatú Carreta",
  "Yaguareté",
  "Ñandú",
  "Puma",
  "Ñandú",
  "Guanaco",
  "Cóndor Andino",
  "Huemul",
  "Pecarí",
  "Venado de las Pampas",
  "Aguará Guazú",
  "Carancho",
  "Zorro Gris",
  "Oso Hormiguero",
  "Mono Carayá",
  "Serpiente Yarará",
  "Lagarto Overo",
  "Gato Montés",
  "Halcón Peregrino",
  "Víbora de la Cruz",
  "Quirquincho",
  "Zorro Colorado",
  "Carpincho",
  "Chajá",
  "Paloma Monte",
  "Gallito de las Rocas",
  "Tucán",
  "Caimán del Orinoco",
  "Boa Constrictora",
  "Armado",
  "Zorrino",
  "Sapo Común",
  "Cucaracha Silvestre",
  "Escorpión Negro",
  "Murciélago",
  "Ratón de Campo",
  "Comadreja",
  "Tarántula",
  "Chinche",
  "Tero",
  "Lechuza de las Vizcacheras",
  "Caracol Gigante",
  "Araña del Pastizal",
  "Avispa Patagona",
  "Hormiga León",
  "Alacrán",
  "Mosquito",
  "Liebre Patagónica",
  "Conejo Silvestre",
  "Búho Magallánico",
  "Águila Mora",
  "Loro Barranquero",
  "Gavilán Mixto",
  "Paloma Picazuro",
  "Caburé",
  "Faisán",
  "Carpintero Real",
  "Cotorra",
];
